baseURL = 'https://kinohui.github.io/'
locale = 'zh-cn'
title = "Kino's Blog"
theme = 'PaperMod'

[params]
  env = "production"
  description = "个人博客"
  defaultTheme = "auto"
  ShowShareButtons = true
  ShowReadingTime = true
  ShowPostNavLinks = true
  ShowBreadCrumbs = true
  ShowCodeCopyButtons = true
  ShowToc = true

  [params.assets]
    theme = "#00be91"

  [params.homeInfoParams]
    Title = "Hi, I'm Kino"
    Content = "Write code, read source."

  [[params.socialIcons]]
    name = "github"
    url = "https://github.com/KinoHui"

[menu]
  [[menu.main]]
    identifier = "archives"
    name = "归档"
    url = "/archives/"
    weight = 10
  [[menu.main]]
    identifier = "tags"
    name = "标签"
    url = "/tags/"
    weight = 20
  [[menu.main]]
    identifier = "categories"
    name = "分类"
    url = "/categories/"
    weight = 30

[outputs]
  home = ["HTML", "RSS", "JSON"]

[markup]
  [markup.highlight]
    codeFences = true
    guessSyntax = true
    lineNos = false
    style = "dracula"
